# fly.toml app configuration file generated for kevin-gastelum on 2023-11-05T21:22:47-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kevin-gastelum"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
